// DO NOT EDIT THIS: This file was generated by the Pyrin Typescript Generator
import { z } from "zod";

export const Track = z.object({
  name: z.string(),
  artists: z.array(z.string()),
  album: z.string(),
  coverUrl: z.string(),
});
export type Track = z.infer<typeof Track>;

export const Status = z.object({
  currentTrack: Track,
  isPlaying: z.boolean(),
  volume: z.number(),
  mute: z.boolean(),
  queueIndex: z.number(),
  numTracks: z.number(),
  position: z.number(),
  duration: z.number(),
});
export type Status = z.infer<typeof Status>;

export const List = z.object({
  id: z.string(),
  name: z.string(),
});
export type List = z.infer<typeof List>;

export const GetLists = z.object({
  lists: z.array(List),
});
export type GetLists = z.infer<typeof GetLists>;

export const SeekBody = z.object({
  skip: z.number(),
});
export type SeekBody = z.infer<typeof SeekBody>;

