// DO NOT EDIT THIS: This file was generated by the Pyrin Typescript Generator
import { z } from "zod";

// Name: List
export const List = z.object({
  // Name: List.id
  "id": z.string(),
  // Name: List.name
  "name": z.string(),
});
export type List = z.infer<typeof List>;

// Name: GetLists
export const GetLists = z.object({
  // Name: GetLists.lists
  "lists": z.array(List),
});
export type GetLists = z.infer<typeof GetLists>;

// Name: Track
export const Track = z.object({
  // Name: Track.name
  "name": z.string(),
  // Name: Track.artists
  "artists": z.array(z.string()),
  // Name: Track.album
  "album": z.string(),
  // Name: Track.coverUrl
  "coverUrl": z.string(),
});
export type Track = z.infer<typeof Track>;

// Name: GetQueue
export const GetQueue = z.object({
  // Name: GetQueue.tracks
  "tracks": z.array(Track),
});
export type GetQueue = z.infer<typeof GetQueue>;

// Name: SeekBody
export const SeekBody = z.object({
  // Name: SeekBody.skip
  "skip": z.number(),
});
export type SeekBody = z.infer<typeof SeekBody>;

// Name: Status
export const Status = z.object({
  // Name: Status.currentTrack
  "currentTrack": Track,
  // Name: Status.isPlaying
  "isPlaying": z.boolean(),
  // Name: Status.volume
  "volume": z.number(),
  // Name: Status.mute
  "mute": z.boolean(),
  // Name: Status.queueIndex
  "queueIndex": z.number(),
  // Name: Status.numTracks
  "numTracks": z.number(),
  // Name: Status.position
  "position": z.number(),
  // Name: Status.duration
  "duration": z.number(),
});
export type Status = z.infer<typeof Status>;

