// DO NOT EDIT THIS: This file was generated by the Pyrin Typescript Generator
import { z } from "zod";

export const Set = z.object({
  name: z.string(),
  index: z.number(),
});
export type Set = z.infer<typeof Set>;

export const Sets = z.object({
  sets: z.array(Set),
});
export type Sets = z.infer<typeof Sets>;

export const Status = z.object({
  trackName: z.string(),
  trackArtist: z.string(),
  trackAlbum: z.string(),
  isPlaying: z.boolean(),
  volume: z.number(),
  mute: z.boolean(),
  queueIndex: z.number(),
  numTracks: z.number(),
});
export type Status = z.infer<typeof Status>;

